
[[pages]]
name = "InÃ­cio"
path = "Home.py"
icon = "ğŸ "


[[pages]]
name = "DetecÃ§Ã£o de Imagens"
path = "sections/1_Image_Detection.py"
icon = "ğŸ–¼ï¸"


[[pages]]
name = "DetecÃ§Ã£o em Tempo Real"
path = "sections/2_Realtime_Detection.py"
icon = "ğŸ“·"


[[pages]]
name = "DetecÃ§Ã£o de VÃ­deo"
path = "sections/3_Video_Detection.py"
icon = "ğŸ¥"


[[pages]]
name = "Captura de Tela em Tempo Real"
path = "sections/4_Realtime_Screen_Capture.py"
icon = "ğŸ–¥ï¸"

